# Generated by Django 4.0.3 on 2022-04-05 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogoapp', '0002_rename_film_films_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='films',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogoapp.author'),
        ),
        migrations.AlterField(
            model_name='films',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
