# Generated by Django 4.0.3 on 2022-04-05 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogoapp', '0003_films_author_alter_films_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Author',
            new_name='Director',
        ),
    ]
