# Generated by Django 4.0.3 on 2022-04-05 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogoapp', '0006_genre_alter_films_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='author',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogoapp.director'),
        ),
    ]
