# Generated by Django 4.0.3 on 2022-04-05 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogoapp', '0009_remove_genre_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='films',
            name='genre',
        ),
    ]
